/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DuplicatesRouteImport } from './routes/duplicates'
import { Route as CleanRouteImport } from './routes/clean'
import { Route as IndexRouteImport } from './routes/index'

const DuplicatesRoute = DuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanRoute = CleanRouteImport.update({
  id: '/clean',
  path: '/clean',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clean': typeof CleanRoute
  '/duplicates': typeof DuplicatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clean': typeof CleanRoute
  '/duplicates': typeof DuplicatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clean': typeof CleanRoute
  '/duplicates': typeof DuplicatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clean' | '/duplicates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clean' | '/duplicates'
  id: '__root__' | '/' | '/clean' | '/duplicates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CleanRoute: typeof CleanRoute
  DuplicatesRoute: typeof DuplicatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/duplicates': {
      id: '/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clean': {
      id: '/clean'
      path: '/clean'
      fullPath: '/clean'
      preLoaderRoute: typeof CleanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CleanRoute: CleanRoute,
  DuplicatesRoute: DuplicatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
